### PR TITLE
implement a very simple plugin system using yapsy

### PR DESCRIPTION
**Pull request by lstern**
Supporting plugins using yapsy so extra features could be added using plugins instead of forking the app.

### CODE REVIEW

**Comment by lstern** [comment]
just realized that yapsy requires plugins to be bundled with him

**Comment by kakaroto** [comment]
I like the idea of using a plugin system. yapsy seems easy enough, and I really don't think plugins need to be bundled with yapsy. Just needs to be in SWParser directory, or whatever directory you've set in the code.
Anyways, your code wasn't working at all because of the wrong-number-of-args errors I pointed out in the commit comments. I suggest you test your changes before you commit them.

**Comment by lstern** [comment]
I saw some reports of people having trouble using yapsy plugins with py2exe and pyinstaller. I will do some tests tomorrow as python should load pyc files without issues. If everything works fine, I'll submit a **proper** pull request

**Comment by kakaroto** [comment]
Ah, with py2exe might be different, good point. But I think it wouldn't be a big issue, we could have the plugins directory bundled with the exe as is (as a separate directory with .py files, instead of being inside the library.zip file), it would then work in that case.
By the way, I just noticed my comments on the commit were also put in the push request. In case you didn't know, they were comment on specific lines of code, so check the commit itself to see what each comment is about.
Thanks.

**Pull request closed without merging**
