### PR TITLE
Implement a very simple plugin system (yapsy)

### PR DESCRIPTION
**Pull request by lstern**
implemented yapsy and created a demo plugin.

### CODE REVIEW

**Comment by kakaroto** [comment]
Awesome, that looks good. I haven't tested it yet, but I like how simplistic it is. I almost had no comments this time, but it is already mergeable even without fixing what I mentioned in the commit.
Thanks!

**Comment by lstern** [comment]
I overlooked the possibility of a  faulty plugin breaking other plugins, good catch. I was hoping that DemoPlugin would be the only plugin deployed with the SW Parser so I had hard-coded the names trying to avoid unnecessary complexity ( I was expecting people dropping python scripts in the plugins folder to do whatever they need to do)

**Comment by kakaroto** [comment]
Cool, I see you used glob, so I assume using the wildcard in the data_files variable didn't work? Either way, it's perfect. I'll merge it. I just had one small comment without consequence.
I think I will make the rune&monster extraction into a plugin and the visitor as well.

**Comment by lstern** [comment]
Yeah, the wildcard didn't work I almost moved those features to plugins but wanted minimize my intrusion level since I'm still getting used to python, totally different environment for me.

**Comment by kakaroto** [comment]
Ok, thanks for testing/confirming the wildcard didn't work (online, it was conflicting as some said it works, some said it didn't). No worries about moving the features, intrusion level was indeed pretty minimal and it's nice. If you wanted to do it, you could have just done it as a separate commit, then I could have taken some commits and left the others.
By the you seem to be getting used to python quickly and you learn fast, so good job! :)

**Comment by dustinbarnes** [comment]
In case others run into this:

```
[21:19:28 /ws/ext/SWParser](git:master)
$ python --version
Python 2.7.10

[21:19:32 /ws/ext/SWParser](git:master)
$ python SWProxy.py 
Traceback (most recent call last):
  File "SWProxy.py", line 6, in <module>
    from yapsy.PluginManager import PluginManager
ImportError: No module named yapsy.PluginManager
```

If you get this, you might need to: 

```
[21:21:26 /ws/ext/SWParser](git:master^)
$ sudo pip install yapsy
Collecting yapsy
  Downloading Yapsy-1.11.223.tar.gz (80kB)
    100% |████████████████████████████████| 81kB 3.3MB/s 
Installing collected packages: yapsy
  Running setup.py install for yapsy ... done
Successfully installed yapsy-1.11.223
```

**Comment by kakaroto** [comment]
Oh yeah, thanks! The new dependency needs to be added to the README file. I'll do that right now.

**Pull request merged**
