### PR TITLE
unicode support in CSV with wizard_name

### PR DESCRIPTION
**Pull request by stanleykylee**
ascii encode doesn't handle certain characters
codecs.open allows for unicode files to be written to

### CODE REVIEW

**Comment by kakaroto** [comment]
Humm, that's interesting, and this works for users with kanji in their names ? is there any risk that it would fail at some point for some use case?

**Comment by stanleykylee** [comment]
yes, we've been using it in my fork with no issues thus far. though I can't say I've tested every use case, but users with various different unicode texts have been written to the csv with no issues.
the only small issue is excel no longer detects the file as csv and you have to manually input the file and tell excel that it is comma delimited.

**Comment by kakaroto** [comment]
That's good to know, thanks for the trick! I think what needs to be done is to change the 'f.write' into using the csv module, so if a username has a comma or a quotation mark in it for example, it will get escaped and it won't screw up everything, I don't know how unicode chars could also affect the csv content, but that should help fix all possible issues.

**Comment by stanleykylee** [comment]
I agree with you. unicodecsv should solve this, but I haven't looked into it much. if I have some time this weekend I may try it. we needed something quick so I didn't alter too much of what you had.

**Pull request merged**
