### PR TITLE
#19 using the csv module

### PR DESCRIPTION
**Pull request by lstern**
there was no point porting user info to the csv module.

### CODE REVIEW

**Comment by kakaroto** [comment]
I really like what you did, thanks a lot! There's just a couple of fixes to be done (mostly the one about runes csv missing the equipped runes).
Good job in getting familiar with python so fast! :)

**Comment by lstern** [comment]
fixed the mob's runes (missed because when you open the csv everything seems ok, next time I'll use a diff), converted wizard info to the new csv model.

I had problems trying to make codecs work. I guess its because csv does not support unicode out of the box.  Tested this solution visiting one of the top asian guys at world boss and everything was fine.

**Comment by kakaroto** [comment]
lol, not even finished reviewing your previous commit that you already fixed everything I mentioned.

**Comment by kakaroto** [comment]
Looks great overall, I've merged it! I've also added a AUTHORS file and added your name to it. Thanks!

**Comment by lstern** [comment]
Thanks!

**Pull request merged**
